services:
  database:
    container_name: todo-database
    image: postgres:latest
    restart: on-failure:5
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql
    networks:
      - internal

  api:
    container_name: todo-api
    image: ${REGISTRY}/api:latest
    restart: on-failure:5
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}
    depends_on:
      - database
    networks:
      - internal

volumes:
  database:
    name: todo-database
    external: true

networks:
  internal:
    name: todo-network
    external: true
